# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Imager-DTP
version:      0.03
version_from: lib/Imager/DTP.pod
installdirs:  site
requires:
    Imager:                        0.39
    Imager::Matrix2d:              0
    Test::More:                    0
    utf8:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
